version: '2'
services:
  app:
    image: "hashcat-wpa-server"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        branch: intel-cpu
    ports:
     - "9111:80"
    environment:
       - "HASHCAT_ADMIN_USER=${HASHCAT_ADMIN_USER}"
       - "HASHCAT_ADMIN_PASSWORD=${HASHCAT_ADMIN_PASSWORD}"
       - "TERM=xterm"
    volumes:
      - $HOME/hashcat_database/:/hashcat-wpa-server/database/
    restart: always