version: '2'
services:
  app:
    image: "hashcat-wpa-server"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "80:80"
     - "9000:80"
    environment:
       - "HASHCAT_ADMIN_USER=${HASHCAT_ADMIN_USER}"
       - "HASHCAT_ADMIN_PASSWORD=${HASHCAT_ADMIN_PASSWORD}"
       - "TERM=xterm"
    restart: always