version: '3.7'
services:
  hashcat-wpa-server:
    image: "hashcat-wpa-server:pocl"
    build:
      context: ..
      dockerfile: docker/Dockerfile-pocl
    ports:
     - "9111:80"
    environment:
       - "HASHCAT_ADMIN_USER=${HASHCAT_ADMIN_USER}"
       - "HASHCAT_ADMIN_PASSWORD=${HASHCAT_ADMIN_PASSWORD}"
       - "TERM=xterm"
    volumes:
      - hashcat-db:/root/hashcat-wpa-server/database
      - hashcat-migrations:/root/hashcat-wpa-server/migrations
      - hashcat-cache:/root/.hashcat
    restart: always


volumes:
  hashcat-db:
  hashcat-migrations:
  hashcat-cache:
