version: '3.7'
services:
  app:
    image: "hashcat-wpa-server:latest"
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        branch: latest
    ports:
     - "9111:80"
    environment:
       - "HASHCAT_ADMIN_USER=${HASHCAT_ADMIN_USER}"
       - "HASHCAT_ADMIN_PASSWORD=${HASHCAT_ADMIN_PASSWORD}"
       - "TERM=xterm"
    volumes:
      - $HOME/hashcat_database/:/hashcat-wpa-server/database/
    restart: always
