version: '3.7'

services:
  hashcat-wpa-server:
    image: "hashcat-wpa-server:latest"
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        branch: latest
    ports:
     - "9111:80"
    environment:
       - "HASHCAT_ADMIN_USER=${HASHCAT_ADMIN_USER}"
       - "HASHCAT_ADMIN_PASSWORD=${HASHCAT_ADMIN_PASSWORD}"
       - "TERM=xterm"
    volumes:
      - hashcat-database:/root/hashcat-wpa-server/database
      - hashcat-wordlists:/root/hashcat-wpa-server/wordlists/user
      - hashcat-migrations:/root/hashcat-wpa-server/migrations
      - hashcat-cache:/root/.hashcat
    restart: always


volumes:
  hashcat-database:
  hashcat-wordlists:
  hashcat-migrations:
  hashcat-cache:
